package org.indilib.i4j.client.ui;

/*
 * #%L
 * INDI for Java Client UI Library
 * %%
 * Copyright (C) 2013 - 2014 indiforjava
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Lesser Public License for more details.
 * 
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program. If not, see
 * <http://www.gnu.org/licenses/lgpl-3.0.html>.
 * #L%
 */

import java.awt.Dimension;
import java.awt.Toolkit;

import org.indilib.i4j.client.INDINumberElement;

/**
 * A dialog to show information about a INDINumberElement.
 * 
 * @author S. Alonso (Zerjillo) [zerjioi at ugr.es]
 * @see INDINumberElement
 */
public class INDINumberElementInformationDialog extends javax.swing.JDialog {

    /**
     * serial Version UID.
     */
    private static final long serialVersionUID = -5505202899703572564L;

    /**
     * the number element behind the pannel.
     */
    private INDINumberElement element;

    /**
     * Creates new form INDIPropertyInformationDialog.
     * 
     * @param parent
     *            the parent frame.
     * @param modal
     *            should the dialog be modal
     * @param element
     *            the number element behind the pannel.
     */
    public INDINumberElementInformationDialog(java.awt.Frame parent, boolean modal, INDINumberElement element) {
        super(parent, modal);
        initComponents();

        this.element = element;

        pack();

        int width = 400;
        int height = getHeight();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        setBounds((dim.width - width) / 2, (dim.height - height) / 2, width, height);

    }

    /**
     * show the dialog.
     */
    public void showDialog() {
        format.setText(element.getNumberFormat());
        min.setText(element.getMinAsString());
        max.setText(element.getMaxAsString());
        step.setText(element.getStepAsString());

        setTitle("\"" + element.getLabel() + "\" information");

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        format = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        min = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        max = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        step = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 0, 5));
        jPanel2.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jPanel1.setLayout(new java.awt.BorderLayout(5, 0));

        jLabel1.setText("Format:");
        jPanel1.add(jLabel1, java.awt.BorderLayout.WEST);

        format.setEditable(false);
        jPanel1.add(format, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel1);

        jPanel3.setLayout(new java.awt.BorderLayout(5, 0));

        jLabel2.setText("Minimum:");
        jPanel3.add(jLabel2, java.awt.BorderLayout.WEST);

        min.setEditable(false);
        jPanel3.add(min, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout(5, 0));

        jLabel3.setText("Maximum:");
        jPanel4.add(jLabel3, java.awt.BorderLayout.WEST);

        max.setEditable(false);
        jPanel4.add(max, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout(5, 0));

        jLabel4.setText("Step:");
        jPanel5.add(jLabel4, java.awt.BorderLayout.WEST);

        step.setEditable(false);
        jPanel5.add(step, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/indilib/i4j/client/ui/images/cross.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel6.add(close);

        getContentPane().add(jPanel6, java.awt.BorderLayout.PAGE_END);

        pack();
    } // </editor-fold>//GEN-END:initComponents

    /**
     * close the dialog.
     * 
     * @param evt
     *            the event triggering the action.
     */
    private void closeActionPerformed(java.awt.event.ActionEvent evt) { // GEN-FIRST:event_closeActionPerformed
        this.setVisible(false);
    } // GEN-LAST:event_closeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;

    private javax.swing.JTextField format;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JLabel jLabel4;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel2;

    private javax.swing.JPanel jPanel3;

    private javax.swing.JPanel jPanel4;

    private javax.swing.JPanel jPanel5;

    private javax.swing.JPanel jPanel6;

    private javax.swing.JTextField max;

    private javax.swing.JTextField min;

    private javax.swing.JTextField step;
    // End of variables declaration//GEN-END:variables
}
